name: flutter_example_notification_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  #Core
  change_app_package_name: ^1.0.0

  #State Management
  get: ^4.6.1

  #Firebase
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.8

  #Notification
  flutter_local_notifications: ^9.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
